apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8081        # Service port inside cluster
      targetPort: 8081  # Matches containerPort
      nodePort: 30400   # Changed from 30080 to 30400 (free)
