apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30400   # Avoid conflicts with Jenkins, Prometheus, Grafana, SonarQube
